favicon: null
name: William Ashley Boehler
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 1
  brandStrength: 0.5
  lightness: 0
  brandColors:
    - '#000000'
    - '#84befc'
    - '#307edd'
    - '#e29e4f'
    - '#916f5d'
  rhythmicContrast: 1
typography_spectrum: 0.5988806
layout_spectrum: 0.6725746
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
