name: William Ashley Boehler
favicon: null
layout_spectrum: 0.7537
typography_spectrum: 0.28212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#84befc'
    - '#307edd'
    - '#e29e4f'
    - '#916f5d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
